import type { NextPage } from 'next'
import Head from 'next/head'

import { Header, Footer } from '@Components/basic'
import Script from 'next/script';

const index: NextPage = ({}) => {
    return (
        <div>
            <Head>
                <title>Kristal</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
           <main className='contact'>
                <div className="parent">
                    <div className="div1"> 
                        <h1>VoorNaam AchterNaam</h1>
                        <p>Enim sunt fugiat sint ad nulla elit Lorem veniam. Pariatur commodo ex proident tempor deserunt dolor dolor pariatur culpa ullamco id. Deserunt eu aliqua est qui laborum magna cillum sunt. Sunt aliqua velit quis exercitation reprehenderit velit duis cillum nostrud nulla dolor. Ullamco Lorem velit do sunt fugiat occaecat do incididunt officia amet aute occaecat officia ex.</p>
                        <img src="media/CEO.jpg" alt="Trulli" width="500" height="333"></img>
                    </div>

                    <div className="div2"> 
                        <h1>VoorNaam AchterNaam</h1>
                        <p>Enim sunt fugiat sint ad nulla elit Lorem veniam. Pariatur commodo ex proident tempor deserunt dolor dolor pariatur culpa ullamco id. Deserunt eu aliqua est qui laborum magna cillum sunt. Sunt aliqua velit quis exercitation reprehenderit velit duis cillum nostrud nulla dolor. Ullamco Lorem velit do sunt fugiat occaecat do incididunt officia amet aute occaecat officia ex.</p>
                        <img src="media/CEO.jpg" alt="Trulli" width="500" height="333"></img>
                    </div>

                    <div className="div3"> 
                        <h1>VoorNaam AchterNaam</h1>
                        <p>Enim sunt fugiat sint ad nulla elit Lorem veniam. Pariatur commodo ex proident tempor deserunt dolor dolor pariatur culpa ullamco id. Deserunt eu aliqua est qui laborum magna cillum sunt. Sunt aliqua velit quis exercitation reprehenderit velit duis cillum nostrud nulla dolor. Ullamco Lorem velit do sunt fugiat occaecat do incididunt officia amet aute occaecat officia ex.</p>
                        <img src="media/CEO.jpg" alt="Trulli" width="500" height="333"></img>
                    </div>

                    <div className="div4"> 
                        <iframe src="https://maps.google.com/maps?q=pitcairn&t=&z=11&ie=UTF8&iwloc=&output=embed" className='googlemaps'></iframe>
                    </div>

                    <div className="div5"> 
                        <h1>SaKristal</h1>
                        <h2>Contact: SaKristal@hotmail.nl</h2>
                        <h2>Nummer: 123456789</h2>
                        <h2></h2>
                    </div>
                </div>
           </main>
            <Footer />
        </div>
    )
}
export default index