import type { NextPage } from 'next'
import Head from 'next/head'

import { PrismaClient, test } from '@prisma/client'

let data: test[]
let rows

// export async function getServerSideProps() {
//   const prisma = new PrismaClient()
//   return {
//     props: {
//       x: await prisma.test.findMany()
//     }
//   }
// }

// async function saveTest(test: test) {
//   const response = await fetch('/api/addTest',{
//     method: 'POST',
//     body: JSON.stringify(test)
//   })

//   if (!response.ok)
//     throw new Error(response.statusText)

//   return await response.json();
// }

const Home: NextPage = ({ }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <form
        // onSubmit={async (data, e) => {
        //   try {
        //     await saveTest(data);
        //     e.target.reset()
        //   } catch (err) {
        //     console.log(err)
        //   }
        // }}
      >
        <input type="text" name='name' placeholder='name' />
        <input type="number" name="age" placeholder='age' />
        <input type="number" name="score" step={0.1} placeholder='score' />
        <button type='submit'>Subbit</button>
      </form> */}
    </div>
  )
}

export default Home
