import type { NextPage } from 'next'
import Head from 'next/head'

import { Header, Footer } from '@Components/basic'

const Home: NextPage = ({}) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        
      </main>
      <Footer />
    </div>
  )
}

export default Home
