import type { NextPage } from 'next'
import { useRouter } from 'next/router'
import Head from 'next/head'

import { Header, Footer } from '@Components/basic'

const Kristal: NextPage = ({ }) => {
    const router = useRouter()
    const { id } = router.query
    return (
        <div>
            <Head>
                <title>Kristal - {id}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main>
                <h1>{id}</h1>
            </main>
            <Footer />
        </div>
    )
}
export default Kristal