import type { NextPage } from 'next'
import Head from 'next/head'

import { kristallen } from '@prisma/client';
import { useState } from 'react';

import { Header, Footer } from '@Components/basic'

const index: NextPage = ({ }) => {
    return (
        <div>
            <Head>
                <title>Kristal</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main>

            </main>
            <Footer />
        </div>
    )
}
export default index