import type { NextPage } from 'next'
import Head from 'next/head'

import { Header, Footer } from '@Components/basic'

class zodiac {
    symbol:String;
    name:String;
    gloss:String;
    
    constructor(unicode:String, name:String, gloss:String) {
        this.symbol = unicode;
        this.name = name;
        this.gloss = gloss;
    }
    Output() {
        return `${this.symbol} ${this.name} ${this.gloss}`;
    }
}
const zodiacSigns = [
    new zodiac('♈︎︎', "Aries", "Ram"),
    new zodiac('♉︎︎', "", ""),
    new zodiac('♊︎︎', "", ""),
    new zodiac('♋︎︎', "", ""),
    new zodiac('♌︎︎', "", ""),
    new zodiac('♍︎︎', "", ""),
    new zodiac('♎︎︎', "", ""),
    new zodiac('♏︎︎', "", ""),
    new zodiac('♐︎︎', "", ""),
    new zodiac('♑︎︎', "", ""),
    new zodiac('♒︎︎', "", ""),
    new zodiac('♓︎︎', "", ""),
]

const New: NextPage = ({ }) => {
    return (
        <div>
            <Head>
                <title>New kristal</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main>
                <form>
                    <input type="text" name="naam" />
                    <input type="number" name="prijs" step="0.01" />
                    <input type="color" name="kleur" />
                    <input type="text" name="gewicht" />
                    <input type="checkbox" name="transparant" />
                    <select name="zodiac">
                        
                    </select>
                </form>
            </main>
            <Footer />
        </div>
    )
}
export default New